// Server only — site-wide SEO from the dashboard (/admin/seo + Settings), shared by the root layout,
// pages, structured data, llms.txt and the share picture. Everything is read through the no-expiry
// cache, so metadata never costs a database round trip.
import type { Metadata } from "next";
import { cache } from "react";
import type { BrandingSettings } from "@/components/providers/BrandingProvider";
import { CACHE_TAGS, cached, readDoc, readOrFallback } from "@/lib/cache";
import { SITE_URL } from "@/lib/constants";
import { DEFAULT_SEO, SEO_DOC, fillSeoText, normalizeSeo, splitList, type SeoPageId, type SeoSettings } from "./settings";

type OpenGraph = NonNullable<Metadata["openGraph"]>;

// Only used when the owner settings can't be read
export const FALLBACK_SITE_NAME = "GTech";
export const FALLBACK_OWNER_NAME = "Gamal Abdelaty";

/** Picture on shared links for pages without their own (generated by src/app/opengraph-image.tsx). */
export const SHARE_IMAGE = { url: "/opengraph-image", width: 1200, height: 630 } as const;

/** Trimmed text, or undefined for missing/empty values so they never become empty tags. */
export function clean(value: unknown) {
    return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

// ── Raw documents ─────────────────────────────────────────────────────────────

const readSettings = cached(
    async () =>
        (await readDoc<BrandingSettings>("site_content", "settings")) ?? (await readDoc<BrandingSettings>("site_content", "hero")),
    "settings",
    [CACHE_TAGS.settings]
);

/** Owner settings (site_content/settings, or the older hero document). `null` if unreadable. */
export const getSiteSettings = cache(async () => readOrFallback("settings", readSettings, null));

const readSeo = cached(async () => readDoc<Record<string, unknown>>(SEO_DOC.collection, SEO_DOC.id), "seo", [CACHE_TAGS.seo]);

/** SEO settings from /admin/seo (defaults for anything missing or unreadable). */
export const getSeoSettings = cache(async (): Promise<SeoSettings> => normalizeSeo(await readOrFallback("SEO settings", readSeo, null)));

// ── Resolved values ───────────────────────────────────────────────────────────

export interface SiteSeo {
    seo: SeoSettings;
    settings: BrandingSettings | null;
    siteName: string;
    ownerName: string;
    ownerTitle?: string;
    /** Business name for Google and AI assistants */
    businessName: string;
    /** Main phone, international format (+201024531452) */
    phone?: string;
    /** Phone as people write it (+20 102 453 1452) */
    phoneDisplay?: string;
    /** WhatsApp digits (201024531452) */
    whatsapp?: string;
    email?: string;
    city?: string;
    logo?: string;
    /** Home page title (also used by pages without a title of their own) */
    defaultTitle: string;
    /** Next.js title pattern (%s = page title) */
    titleTemplate: string;
    /** Site-wide description (pages without their own) */
    description?: string;
    /** Home page description */
    homeDescription?: string;
    keywords: string[];
    /** Site-wide keywords plus the home page ones */
    homeKeywords: string[];
    ogSiteName: string;
    twitterHandle?: string;
    shareTagline: string;
    /** Fills {siteName} {ownerName} {phone} {city} in any SEO text */
    fill: (text: string, vars?: Record<string, string>) => string;
}

const digits = (value: unknown) => String(value ?? "").replace(/\D/g, "");

/** Next.js puts the page title where %s is; a pattern without it would give every page the same title. */
function toTitleTemplate(pattern: string, siteName: string) {
    if (!pattern) return `%s | ${siteName}`;
    return pattern.includes("%s") ? pattern : `%s | ${pattern}`;
}

/** Everything SEO-related, with SEO fields left empty falling back to Settings. Read once per request. */
export const getSiteSeo = cache(async (): Promise<SiteSeo> => {
    const [seo, settings] = await Promise.all([getSeoSettings(), getSiteSettings()]);
    const business = seo.business;
    const siteName = clean(settings?.siteName) ?? FALLBACK_SITE_NAME;
    const ownerName = clean(business.founderName) ?? clean(settings?.ownerName) ?? FALLBACK_OWNER_NAME;

    const whatsapp = digits(business.whatsapp) || digits(settings?.whatsappNumber) || undefined;
    const phoneDigits = digits(business.phone) || whatsapp;
    const phone = phoneDigits ? `+${phoneDigits}` : undefined;
    // Settings keep a nicely spaced version of the WhatsApp number; an SEO override is shown as typed
    const phoneDisplay = clean(business.phone) ?? clean(settings?.phoneDisplay) ?? phone;
    const city = clean(business.city);

    const vars: Record<string, string> = { siteName, ownerName, phone: phoneDisplay ?? "", city: city ?? "" };
    const fill = (text: string, extra?: Record<string, string>) => fillSeoText(text, { ...vars, ...extra });
    const handle = seo.twitterHandle.trim().replace(/^@+/, "");

    return {
        seo,
        settings,
        siteName,
        ownerName,
        ownerTitle: clean(settings?.ownerTitle),
        businessName: clean(business.name) ?? siteName,
        phone,
        phoneDisplay,
        whatsapp,
        email: clean(business.email) ?? clean(settings?.emailAddress),
        city,
        logo: clean(settings?.siteLogo),
        defaultTitle: fill(seo.pages.home.title) || fill(seo.siteTitle || DEFAULT_SEO.siteTitle) || siteName,
        titleTemplate: toTitleTemplate(fill(seo.titleTemplate, { title: "%s" }), siteName),
        description: fill(seo.description) || undefined,
        homeDescription: fill(seo.pages.home.description) || fill(seo.description) || undefined,
        keywords: splitList(fill(seo.keywords)),
        homeKeywords: [...new Set([...splitList(fill(seo.keywords)), ...splitList(fill(seo.pages.home.keywords))])],
        ogSiteName: fill(seo.shareSiteName) || siteName,
        twitterHandle: handle ? `@${handle}` : undefined,
        shareTagline: fill(seo.shareTagline),
        fill,
    };
});

/**
 * The part of the share card (WhatsApp, Facebook, LinkedIn, X) every page has in common.
 * Title and description are left out on purpose: Next.js then uses each page's own.
 *
 * Next.js replaces a parent's `openGraph` instead of merging it, so a page that sets its own
 * must start from this: `openGraph: { ...(await getSiteOpenGraph()), images: [cover] }`.
 */
export async function getSiteOpenGraph() {
    const { ogSiteName } = await getSiteSeo();
    return {
        type: "website",
        locale: "en_US",
        url: "./",
        siteName: ogSiteName,
        images: [{ ...SHARE_IMAGE, alt: ogSiteName }],
    } satisfies OpenGraph;
}

/** Title, description, keywords and share card of a main page, from /admin/seo → Pages. */
export async function pageMetadata(pageId: Exclude<SeoPageId, "home">, extra: Metadata = {}): Promise<Metadata> {
    const [site, openGraph] = await Promise.all([getSiteSeo(), getSiteOpenGraph()]);
    const page = site.seo.pages[pageId];
    const title = site.fill(page.title) || undefined;
    const description = site.fill(page.description) || site.description;
    const keywords = [...new Set([...splitList(site.fill(page.keywords)), ...site.keywords])];

    return {
        title,
        description,
        keywords: keywords.length > 0 ? keywords : undefined,
        alternates: { canonical: "./" },
        openGraph,
        ...extra,
    };
}

/** Absolute URL on this site. */
export function absoluteUrl(path: string) {
    return new URL(path, SITE_URL).toString();
}
