// Server only — site-wide SEO values from the dashboard, shared by the root layout and pages.
import type { Metadata } from "next";
import { cache } from "react";
import type { BrandingSettings } from "@/components/providers/BrandingProvider";
import type { CopyKey } from "@/config/copy";
import { getCopy } from "@/lib/copy/server";
import { getDocument } from "@/lib/server-utils";

type OpenGraph = NonNullable<Metadata["openGraph"]>;

// Only used when the owner settings can't be read
export const FALLBACK_SITE_NAME = "GTech";
export const FALLBACK_OWNER_NAME = "Gamal Abdelaty";

/** Picture on shared links for pages without their own (generated by src/app/opengraph-image.tsx). */
export const SHARE_IMAGE = { url: "/opengraph-image", width: 1200, height: 630 } as const;

/** Owner settings (site_content/settings, or the older hero document), read once per request. */
export const getSiteSettings = cache(
    async () =>
        (await getDocument<BrandingSettings>("site_content", "settings")) ??
        (await getDocument<BrandingSettings>("site_content", "hero"))
);

/** Trimmed text, or undefined for missing/empty values so they never become empty tags. */
export function clean(value: unknown) {
    return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

/** Next.js puts the page title where %s is; a pattern without it would give every page the same title. */
function toTitleTemplate(pattern: string, siteName: string) {
    if (!pattern) return `%s | ${siteName}`;
    return pattern.includes("%s") ? pattern : `%s | ${pattern}`;
}

/** Site-wide SEO from Settings and /admin/copy → SEO, read once per request. */
export const getSiteSeo = cache(async () => {
    const [t, settings] = await Promise.all([getCopy(), getSiteSettings()]);
    const siteName = clean(settings?.siteName) ?? FALLBACK_SITE_NAME;
    const text = (key: CopyKey, vars?: Record<string, string>) => t(key, { siteName, ...vars }).trim();
    const handle = text("seo.twitterHandle").replace(/^@+/, "");

    return {
        settings,
        siteName,
        ownerName: clean(settings?.ownerName) ?? FALLBACK_OWNER_NAME,
        defaultTitle: text("seo.defaultTitle") || siteName,
        titleTemplate: toTitleTemplate(text("seo.titleTemplate", { title: "%s" }), siteName),
        description: text("seo.description") || undefined,
        keywords: text("seo.keywords")
            .split(/[,،]/)
            .map((keyword) => keyword.trim())
            .filter(Boolean),
        ogSiteName: text("seo.ogSiteName") || siteName,
        twitterHandle: handle ? `@${handle}` : undefined,
    };
});

/**
 * The part of the share card (WhatsApp, Facebook, LinkedIn, X) every page has in common.
 * Title and description are left out on purpose: Next.js then uses each page's own.
 *
 * Next.js replaces a parent's `openGraph` instead of merging it, so a page that sets its own
 * must start from this: `openGraph: { ...(await getSiteOpenGraph()), images: [cover] }`.
 */
export async function getSiteOpenGraph() {
    const { ogSiteName } = await getSiteSeo();
    return {
        type: "website",
        locale: "en_US",
        url: "./",
        siteName: ogSiteName,
        images: [{ ...SHARE_IMAGE, alt: ogSiteName }],
    } satisfies OpenGraph;
}
