import type { PricingContent } from "./types";

export const PRICING_COLLECTION = "site_content";
export const PRICING_DOC_ID = "pricing";

/**
 * Starting content of the pricing page. It seeded `site_content/pricing`, and the page only
 * falls back to it when the database can't be read — the dashboard is the source of truth.
 */
export const DEFAULT_PRICING: PricingContent = {
    seo: {
        title: "Pricing & packages | GTech",
        keywords: "GTech, pricing, website packages, website prices, Shopify store, custom online store, booking system, mobile app, ERP, CRM, business analysis, Shopify themes, hosting",
        description: "Clear prices in US dollars for websites, online stores, booking systems, mobile apps, ERP and CRM systems, Shopify themes and hosting from GTech.",
    },
    header: {
        eyebrow: "GTech",
        title: "Web services & digital solutions packages",
        description: "Modern technical solutions, competitive prices, and a visual identity that represents you.",
    },
    offer: {
        enabled: true,
        text: "Limited-time discounts on paid add-ons.",
    },
    labels: {
        currency: "USD",
        customQuote: "Custom quote",
        request: "Request",
        requestQuote: "Request a quote",
        featured: "Recommended",
        pages: "Pages",
        hosting: "Hosting",
        hostingCost: "Hosting cost",
        discount: "{percent}% off",
        originalPrice: "Original price",
        call: "Call",
        whatsapp: "WhatsApp",
        email: "Email",
        sendEmail: "Send email",
        priceFrom: "From",
    },
    sections: {
        addons: {
            title: "Paid add-ons",
            description: "Extras you can add to your package, at limited-time discounts.",
        },
        info: {
            title: "Good to know",
            description: "",
        },
        faq: {
            title: "Frequently asked questions",
            description: "",
        },
        contact: {
            title: "Contact us",
            description: "We're here to answer your questions and start your project.",
        },
        services: {
            description: "Starting prices. The final quote depends on the modules and scope you need; tell us what you need and we'll confirm it.",
            title: "Business systems & services",
        },
        packages: {
            description: "Packages for the most common projects, each with a clear price.",
            title: "Website & app packages",
        },
    },
    packages: [
        {
            id: "landing-page",
            name: "Landing page",
            price: 350,
            customQuote: false,
            priceFrom: false,
            description: "Design and domain connection included. Extremely fast and built to turn ad traffic into leads.",
            pages: "1 long page",
            hosting: "Fast global hosting",
            hostingCost: "Free (domain ~$12/year)",
            featured: false,
            visible: true,
        },
        {
            id: "restaurant-menu",
            name: "Restaurant menu (QR code)",
            price: 300,
            customQuote: false,
            priceFrom: false,
            description: "Very fast on mobile, loads well on weak connections, and you update items and prices yourself.",
            pages: "Up to 3 pages + full menu",
            hosting: "Fast global hosting",
            hostingCost: "Free (domain ~$12/year)",
            featured: false,
            visible: true,
        },
        {
            id: "portfolio",
            name: "Portfolio",
            price: 450,
            customQuote: false,
            priceFrom: false,
            description: "Ideal for designers, engineers and consultants, with a distinctive personal design.",
            pages: "Up to 5 pages",
            hosting: "Fast global hosting",
            hostingCost: "Free (domain ~$12/year)",
            featured: false,
            visible: true,
        },
        {
            id: "company-website",
            name: "Company website",
            price: 900,
            customQuote: false,
            priceFrom: false,
            description: "A contact form, Google Map, social links and a dashboard to edit your content yourself.",
            pages: "Up to 8 pages",
            hosting: "Cloud hosting",
            hostingCost: "Free tier, then ~$20/month",
            featured: true,
            visible: true,
        },
        {
            id: "blog",
            name: "Professional blog / news site",
            price: 1000,
            customQuote: false,
            priceFrom: false,
            description: "Fast article pages, categories and a writing dashboard, structured for search engines.",
            pages: "Unlimited articles + up to 6 pages",
            hosting: "Cloud hosting + database",
            hostingCost: "Free tier, then ~$20/month",
            featured: false,
            visible: true,
        },
        {
            id: "shopify-store",
            name: "Online store (Shopify)",
            price: 850,
            customQuote: false,
            priceFrom: false,
            description: "Store setup, theme design, payments and shipping. Shopify's plan is paid monthly to Shopify.",
            pages: "Unlimited products (we add up to 30)",
            hosting: "Included in your Shopify plan",
            hostingCost: "From $29/month",
            featured: false,
            visible: true,
        },
        {
            id: "custom-store",
            name: "Custom online store",
            price: 2200,
            customQuote: false,
            priceFrom: false,
            description: "Your own store with online payments, full data ownership, and no platform fees or sales commission.",
            pages: "Unlimited products (we add up to 30)",
            hosting: "Cloud hosting + database",
            hostingCost: "~$20–$40/month",
            featured: false,
            visible: true,
        },
        {
            id: "booking-system",
            name: "Booking system",
            price: 1900,
            customQuote: false,
            priceFrom: false,
            description: "Custom-built to prevent double bookings and manage staff shifts, with reminders for your customers.",
            pages: "Up to 6 pages + admin dashboard",
            hosting: "Cloud hosting + database",
            hostingCost: "Free tier, then ~$25/month",
            featured: false,
            visible: true,
        },
        {
            id: "directory-site",
            name: "Real-estate / directory site",
            price: 2600,
            customQuote: false,
            priceFrom: false,
            description: "A dashboard to add listings, with advanced search and filters for your visitors.",
            pages: "Up to 8 pages + admin dashboard",
            hosting: "Cloud hosting + database",
            hostingCost: "Free tier, then ~$25/month",
            featured: false,
            visible: true,
        },
        {
            id: "website-to-app",
            name: "Turn your website into an app",
            price: 500,
            customQuote: false,
            priceFrom: false,
            description: "Your existing website as an Android and iOS app, published on Google Play and the App Store.",
            pages: "Your website's pages",
            hosting: "Google Play & App Store",
            hostingCost: "Store fees: $25 once + $99/year",
            featured: false,
            visible: true,
        },
        {
            id: "mobile-app",
            name: "Mobile app (Android & iOS)",
            price: 2500,
            customQuote: false,
            priceFrom: true,
            description: "A fast, native-feeling app for Android and iOS built around your idea, with a dashboard to manage it.",
            pages: "Up to 10 screens",
            hosting: "App stores + cloud backend",
            hostingCost: "Store fees + backend from ~$25/month",
            featured: false,
            visible: true,
        },
    ],
    addons: [
        {
            id: "ai-chatbot",
            name: "AI agent chatbot",
            description: "Answers your customers 24/7 and collects their name and number.",
            originalPrice: 450,
            price: 300,
            customQuote: false,
            featured: false,
            visible: true,
        },
        {
            id: "seo-setup",
            name: "SEO & sitemap setup",
            description: "Sitemap, structured data and Google Search Console setup.",
            originalPrice: 150,
            price: 100,
            customQuote: false,
            featured: false,
            visible: true,
        },
        {
            id: "dark-mode",
            name: "Dark mode",
            description: "A light and dark theme toggle.",
            originalPrice: 100,
            price: 60,
            customQuote: false,
            featured: false,
            visible: true,
        },
        {
            id: "bilingual",
            name: "Bilingual site",
            description: "A second language (for example Arabic and English) with a dual dashboard.",
            originalPrice: 350,
            price: 250,
            customQuote: false,
            featured: false,
            visible: true,
        },
    ],
    services: [
        {
            id: "business-analysis",
            name: "Business analysis",
            price: 300,
            customQuote: false,
            priceFrom: true,
            description: "We map how your business really works and turn it into clear, prioritized requirements, so you build only what you need.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: false,
            visible: true,
        },
        {
            id: "erp-systems",
            name: "ERP systems",
            price: 4000,
            customQuote: false,
            priceFrom: true,
            description: "One system for inventory, sales, purchasing and accounting, built around your processes. The final price depends on the modules.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: true,
            visible: true,
        },
        {
            id: "crm-systems",
            name: "CRM systems",
            price: 2000,
            customQuote: false,
            priceFrom: true,
            description: "Customers, leads, deals and follow-ups in one place, with reminders, pipelines and sales reports.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: false,
            visible: true,
        },
        {
            id: "web-app",
            name: "Custom web app / dashboard",
            price: 1800,
            customQuote: false,
            priceFrom: true,
            description: "Internal tools and dashboards built around your workflow, with user roles, reports and exports.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: false,
            visible: true,
        },
        {
            id: "whatsapp-api",
            name: "WhatsApp Business API integration",
            price: 400,
            customQuote: false,
            priceFrom: true,
            description: "Automatic replies, order updates and alerts on WhatsApp, connected to your website or CRM.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: false,
            visible: true,
        },
        {
            id: "shopify-themes",
            name: "Professional Shopify themes",
            price: 120,
            customQuote: false,
            priceFrom: true,
            description: "A ready, professional theme installed and set up on your store, far cheaper than the Shopify Theme Store.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: false,
            visible: true,
        },
        {
            id: "custom-shopify-theme",
            name: "Custom Shopify theme",
            price: 1200,
            customQuote: false,
            priceFrom: true,
            description: "A theme designed and built for your brand from scratch: fast, conversion-focused and easy to edit in Shopify.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: false,
            visible: true,
        },
        {
            id: "hosting",
            name: "Hosting",
            price: 80,
            customQuote: false,
            priceFrom: true,
            description: "Yearly hosting for your website or system, set up with your domain, SSL and backups.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: false,
            visible: true,
        },
        {
            id: "maintenance",
            name: "Maintenance & support plan",
            price: 40,
            customQuote: false,
            priceFrom: true,
            description: "Monthly updates, backups, fixes and small edits after your free first year, so everything keeps running.",
            pages: "",
            hosting: "",
            hostingCost: "",
            featured: false,
            visible: true,
        },
    ],
    infoCards: [
        {
            id: "visual-identity",
            title: "Visual identity",
            text: "Every site is designed around your brand, with your colors, logo and fonts. No ready-made templates.",
            visible: true,
        },
        {
            id: "custom-solutions",
            title: "Custom solutions",
            text: "The prices above are for basic and medium packages. Fully custom projects are priced by scope.",
            visible: true,
        },
        {
            id: "maintenance",
            title: "Maintenance & support",
            text: "All packages include one full year of free maintenance: a bug-fix guarantee and stability checks.",
            visible: true,
        },
    ],
    faq: [
        {
            id: "currency",
            question: "Which currency are the prices in?",
            answer: "All prices are in US dollars (USD). Items marked \"From\" start at that price; the final quote depends on the scope.",
            visible: true,
        },
        {
            id: "hosting-cost",
            question: "Is hosting included in the price?",
            answer: "Hosting is paid to the hosting provider, separately from the package price. Each package shows its expected hosting cost, and several run on free hosting.",
            visible: true,
        },
        {
            id: "editing",
            question: "Can I edit the content myself?",
            answer: "Yes. Every website comes with a simple dashboard, so you can update text, images and prices without code.",
            visible: true,
        },
        {
            id: "mobile-apps",
            question: "Do you build mobile apps?",
            answer: "Yes. We can turn your existing website into an Android and iOS app, or build a custom app for both platforms with a dashboard to manage it.",
            visible: true,
        },
        {
            id: "get-started",
            question: "How do I get started?",
            answer: "Press Request on the package or add-on you want and leave your name and number, or call us or message us on WhatsApp. We'll get back to you to discuss the details.",
            visible: true,
        },
    ],
    contact: {
        countryCode: "20",
        numbers: [
            {
                id: "primary",
                label: "Primary",
                number: "01024531452",
                whatsapp: true,
            },
            {
                id: "secondary",
                label: "Secondary",
                number: "01105432048",
                whatsapp: false,
            },
        ],
        email: "montasrrm@gmail.com",
    },
};
