import type { PricingContent } from "./types";

export const PRICING_COLLECTION = "site_content";
export const PRICING_DOC_ID = "pricing";

/**
 * Starting content of the pricing page. It seeded `site_content/pricing`, and the page only
 * falls back to it when the database can't be read — the dashboard is the source of truth.
 */
export const DEFAULT_PRICING: PricingContent = {
    seo: {
        title: "Pricing & packages | GTech",
        description:
            "Website packages, paid add-ons and custom-quote services from GTech: landing pages, company websites, online stores, booking systems, ERP and CRM systems, Shopify themes and hosting.",
        keywords:
            "GTech, pricing, website packages, website prices, Shopify store, WooCommerce, WordPress, booking system, ERP, CRM, business analysis, Shopify themes, hosting",
    },
    header: {
        eyebrow: "GTech",
        title: "Web services & digital solutions packages",
        description: "Modern technical solutions, competitive prices, and a visual identity that represents you.",
    },
    offer: {
        enabled: true,
        text: "Limited-time discounts on paid add-ons.",
    },
    labels: {
        currency: "EGP",
        customQuote: "Custom quote",
        request: "Request",
        requestQuote: "Request a quote",
        featured: "Recommended",
        pages: "Pages",
        stack: "Built with",
        hosting: "Hosting",
        hostingCost: "Hosting cost",
        seo: "SEO",
        editing: "Ease of editing",
        discount: "{percent}% off",
        originalPrice: "Original price",
        call: "Call",
        whatsapp: "WhatsApp",
        email: "Email",
        sendEmail: "Send email",
    },
    sections: {
        packages: {
            title: "Website packages",
            description: "Packages for the most common website projects, each with a clear price.",
        },
        addons: {
            title: "Paid add-ons",
            description: "Extras you can add to your package, at limited-time discounts.",
        },
        services: {
            title: "Custom-quote services",
            description: "Priced by scope. Tell us what you need and we'll prepare a quote.",
        },
        info: {
            title: "Good to know",
            description: "",
        },
        faq: {
            title: "Frequently asked questions",
            description: "",
        },
        contact: {
            title: "Contact us",
            description: "We're here to answer your questions and start your project.",
        },
    },
    packages: [
        {
            id: "landing-page",
            name: "Landing page",
            price: 3000,
            customQuote: false,
            description: "Price includes design and domain connection. Extremely fast, ideal for ads.",
            pages: "One long page",
            stack: "Sveltia CMS + GitHub SSG",
            hosting: "Cloudflare Pages",
            hostingCost: "$0",
            seo: "Excellent",
            editing: "Easy",
            featured: false,
            visible: true,
        },
        {
            id: "restaurant-menu",
            name: "Restaurant menu (QR code)",
            price: 3500,
            customQuote: false,
            description: "Very fast on mobile and loads well on weak connections.",
            pages: "Menu and photos",
            stack: "Sveltia CMS + GitHub SSG",
            hosting: "Cloudflare Pages",
            hostingCost: "$0",
            seo: "Excellent",
            editing: "Easy",
            featured: false,
            visible: true,
        },
        {
            id: "portfolio",
            name: "Portfolio",
            price: 4500,
            customQuote: false,
            description: "Ideal for designers and engineers, with a distinctive personal design.",
            pages: "1–4 pages",
            stack: "Sveltia CMS + GitHub SSG",
            hosting: "Cloudflare / GitHub",
            hostingCost: "$0",
            seo: "Excellent",
            editing: "Easy",
            featured: false,
            visible: true,
        },
        {
            id: "company-website",
            name: "Company website",
            price: 6500,
            customQuote: false,
            description: "Includes a working contact form, Google Map and social links.",
            pages: "5–7 pages",
            stack: "Sveltia CMS + GitHub SSG",
            hosting: "Cloudflare / GitHub",
            hostingCost: "$0",
            seo: "Excellent",
            editing: "Easy",
            featured: true,
            visible: true,
        },
        {
            id: "shopify-store",
            name: "Online store (Shopify)",
            price: 8000,
            customQuote: false,
            description: "Includes store setup, design and integration. The platform is paid monthly.",
            pages: "Unlimited products",
            stack: "Shopify",
            hosting: "Shopify servers",
            hostingCost: "From $29/month",
            seo: "Very good",
            editing: "Very easy",
            featured: false,
            visible: true,
        },
        {
            id: "blog",
            name: "Professional blog / news site",
            price: 8000,
            customQuote: false,
            description: "Includes theme, setup and basic security.",
            pages: "Unlimited archive",
            stack: "WordPress",
            hosting: "Hostinger / Bluehost",
            hostingCost: "$5–$20",
            seo: "Excellent",
            editing: "Very easy",
            featured: false,
            visible: true,
        },
        {
            id: "woocommerce-store",
            name: "Online store (WooCommerce)",
            price: 10000,
            customQuote: false,
            description: "Full data ownership and no platform sales commission.",
            pages: "Unlimited products",
            stack: "WordPress + WooCommerce",
            hosting: "Shared / VPS",
            hostingCost: "$5–$20",
            seo: "Excellent",
            editing: "Easy",
            featured: false,
            visible: true,
        },
        {
            id: "booking-system",
            name: "Booking system",
            price: 12000,
            customQuote: false,
            description: "Custom-built to prevent double bookings and manage shifts.",
            pages: "Calendar, bookings and shifts",
            stack: "Next.js + Supabase",
            hosting: "Vercel + Supabase",
            hostingCost: "Free, then ~$25",
            seo: "Good",
            editing: "Medium",
            featured: false,
            visible: true,
        },
        {
            id: "directory-site",
            name: "Real-estate / directory site",
            price: 15000,
            customQuote: false,
            description: "Includes a dashboard to add listings, with advanced filtering.",
            pages: "Advanced search and filters",
            stack: "Next.js + Supabase",
            hosting: "Vercel + Supabase",
            hostingCost: "Free, then ~$25",
            seo: "Excellent",
            editing: "Medium",
            featured: false,
            visible: true,
        },
    ],
    addons: [
        {
            id: "ai-chatbot",
            name: "AI agent chatbot",
            description: "Answers your customers 24/7.",
            originalPrice: 4000,
            price: 1200,
            customQuote: false,
            featured: false,
            visible: true,
        },
        {
            id: "seo-setup",
            name: "SEO & sitemap setup",
            description: "Sitemap and Google Search Console setup.",
            originalPrice: 500,
            price: 250,
            customQuote: false,
            featured: false,
            visible: true,
        },
        {
            id: "dark-mode",
            name: "Dark mode",
            description: "A light and dark theme toggle.",
            originalPrice: 1000,
            price: 500,
            customQuote: false,
            featured: false,
            visible: true,
        },
        {
            id: "bilingual",
            name: "Bilingual site",
            description: "A second language with a dual dashboard.",
            originalPrice: 2500,
            price: 1250,
            customQuote: false,
            featured: false,
            visible: true,
        },
    ],
    services: [
        {
            id: "business-analysis",
            name: "Business analysis",
            price: null,
            customQuote: true,
            description: "Understanding how your business works and turning it into clear requirements before anything is built.",
            pages: "",
            stack: "",
            hosting: "",
            hostingCost: "",
            seo: "",
            editing: "",
            featured: false,
            visible: true,
        },
        {
            id: "erp-systems",
            name: "ERP systems",
            price: null,
            customQuote: true,
            description: "ERP systems for companies and institutions that bring your operations together in one place.",
            pages: "",
            stack: "",
            hosting: "",
            hostingCost: "",
            seo: "",
            editing: "",
            featured: false,
            visible: true,
        },
        {
            id: "crm-systems",
            name: "CRM systems",
            price: null,
            customQuote: true,
            description: "CRM systems to organize your customers, follow up on leads and track sales.",
            pages: "",
            stack: "",
            hosting: "",
            hostingCost: "",
            seo: "",
            editing: "",
            featured: false,
            visible: true,
        },
        {
            id: "shopify-themes",
            name: "Professional Shopify themes",
            price: null,
            customQuote: true,
            description: "Professional Shopify themes, far cheaper than those in the Shopify Theme Store.",
            pages: "",
            stack: "",
            hosting: "",
            hostingCost: "",
            seo: "",
            editing: "",
            featured: false,
            visible: true,
        },
        {
            id: "hosting",
            name: "Hosting",
            price: null,
            customQuote: true,
            description: "Hosting for your website or system, set up and connected to your domain.",
            pages: "",
            stack: "",
            hosting: "",
            hostingCost: "",
            seo: "",
            editing: "",
            featured: false,
            visible: true,
        },
    ],
    infoCards: [
        {
            id: "visual-identity",
            title: "Visual identity",
            text: "Every site is designed around your brand, with your colors, logo and fonts. No ready-made templates.",
            visible: true,
        },
        {
            id: "custom-solutions",
            title: "Custom solutions",
            text: "The prices above are for basic and medium packages. Fully custom projects are priced by scope.",
            visible: true,
        },
        {
            id: "maintenance",
            title: "Maintenance & support",
            text: "All packages include one full year of free maintenance: a bug-fix guarantee and stability checks.",
            visible: true,
        },
    ],
    faq: [
        {
            id: "currency",
            question: "Which currency are the prices in?",
            answer: "Package and add-on prices are in Egyptian pounds (EGP). Hosting costs are shown in US dollars.",
            visible: true,
        },
        {
            id: "hosting-cost",
            question: "Is hosting included in the price?",
            answer: "Hosting is paid to the hosting provider, separately from the package price. Each package shows its expected hosting cost, and several run on free hosting.",
            visible: true,
        },
        {
            id: "editing",
            question: "Can I edit the content myself?",
            answer: "Yes. Each package shows how easy it is to edit, and most come with a simple content editor so you can update text and images without code.",
            visible: true,
        },
        {
            id: "get-started",
            question: "How do I get started?",
            answer: "Press Request on the package or add-on you want and leave your name and number, or call us or message us on WhatsApp. We'll get back to you to discuss the details.",
            visible: true,
        },
    ],
    contact: {
        countryCode: "20",
        numbers: [
            { id: "primary", label: "Primary", number: "01024531452", whatsapp: true },
            { id: "secondary", label: "Secondary", number: "01105432048", whatsapp: false },
        ],
        email: "",
    },
};
