import type { CopySection } from "@/lib/copy/types";

export const accountCopy = {
    id: "account",
    title: "Accounts (log in, settings, writing articles, editing posts, image editor)",
    description: "Each label starts with where the text appears: log in window, settings page, write page, edit post page or image editor.",
    fields: [
        { key: "loading", label: "Account pages: loading message", default: "Loading…" },

        // Log in / sign up window
        { key: "authLoginTitle", label: "Log in window: title (log in)", default: "Log in" },
        { key: "authSignupTitle", label: "Log in window: title (create account)", default: "Create account" },
        { key: "authNameLabel", label: "Log in window: name field (create account)", default: "Full name" },
        { key: "authNamePlaceholder", label: "Log in window: name field placeholder", default: "Your name" },
        { key: "authEmailLabel", label: "Log in window: email field", default: "Email" },
        { key: "authEmailPlaceholder", label: "Log in window: email field placeholder", default: "name@example.com" },
        { key: "authPasswordLabel", label: "Log in window: password field", default: "Password" },
        { key: "authPasswordHint", label: "Log in window: hint under the password (create account)", default: "At least 6 characters" },
        { key: "authLoginButton", label: "Log in window: log in button", default: "Log in" },
        { key: "authSignupButton", label: "Log in window: create account button", default: "Create account" },
        { key: "authOr", label: "Log in window: divider above the Google button", default: "or" },
        { key: "authGoogle", label: "Log in window: Google button", default: "Continue with Google" },
        { key: "authNoAccount", label: "Log in window: question before the create account link", default: "Don't have an account?" },
        { key: "authToSignup", label: "Log in window: link to switch to create account", default: "Create account" },
        { key: "authHaveAccount", label: "Log in window: question before the log in link", default: "Already have an account?" },
        { key: "authToLogin", label: "Log in window: link to switch to log in", default: "Log in" },
        { key: "authWelcomeBack", label: "Log in window: toast after logging in", default: "Welcome back" },
        { key: "authAccountCreated", label: "Log in window: toast after creating an account", default: "Your account has been created" },
        { key: "authGoogleSuccess", label: "Log in window: toast after logging in with Google", default: "Logged in with Google" },
        { key: "authGoogleCancelled", label: "Log in window: toast when the Google window is closed", default: "Login cancelled" },
        { key: "authErrorCredentials", label: "Log in window: error for a wrong email or password", default: "Incorrect email or password." },
        { key: "authErrorEmailInUse", label: "Log in window: error when the email already has an account", default: "This email is already in use." },
        { key: "authErrorWeakPassword", label: "Log in window: error for a short password", default: "Password must be at least 6 characters." },
        { key: "authErrorGeneric", label: "Log in window: error for any other problem", default: "Couldn't log you in. Please try again." },
        { key: "authErrorNameRequired", label: "Log in window: error when the name is missing (create account)", default: "Please enter your name." },
        { key: "authErrorEmailInvalid", label: "Log in window: error for a missing or invalid email", default: "Please enter a valid email address." },
        { key: "authErrorPasswordRequired", label: "Log in window: error when the password is missing", default: "Please enter your password." },
        { key: "authErrorDomain", label: "Log in window: error when Google log in isn't allowed on this domain", default: "This domain isn't authorized for Google log in. Add it in the Firebase settings." },
        { key: "authErrorGoogle", label: "Log in window: error when Google log in fails", default: "Google log in failed. Please try again." },

        // Box shown on pages that need a signed-in user
        { key: "loginPromptTitle", label: "Log in required box: default title", default: "Log in required" },
        { key: "loginPromptDescription", label: "Log in required box: default text", default: "Please log in to view this page." },
        { key: "loginPromptButton", label: "Log in required box: button", default: "Log in" },

        // Settings page (/settings)
        { key: "settingsSeoTitle", label: "Settings page: Google title", default: "Account settings" },
        { key: "settingsSeoDescription", label: "Settings page: Google description", type: "textarea", default: "Manage your profile and account settings." },
        { key: "settingsLockedTitle", label: "Settings page: title for logged-out visitors", default: "Account settings" },
        { key: "settingsLockedDescription", label: "Settings page: text for logged-out visitors", default: "Log in to manage your profile and account." },
        { key: "settingsTitle", label: "Settings page: title", default: "Settings" },
        { key: "settingsChangePhoto", label: "Settings page: change photo button", default: "Change photo" },
        { key: "settingsNameLabel", label: "Settings page: name field", default: "Full name" },
        { key: "settingsJobLabel", label: "Settings page: job title field", default: "Job title" },
        { key: "settingsJobPlaceholder", label: "Settings page: job title placeholder", default: "e.g. Web developer, graphic designer" },
        { key: "settingsLocationLabel", label: "Settings page: location field", default: "Location" },
        { key: "settingsLocationPlaceholder", label: "Settings page: location placeholder", default: "e.g. Cairo, Egypt" },
        { key: "settingsStatusLabel", label: "Settings page: relationship status field", default: "Relationship status" },
        { key: "settingsStatusSingle", label: "Settings page: relationship status option (single)", default: "Single" },
        { key: "settingsStatusEngaged", label: "Settings page: relationship status option (engaged)", default: "Engaged" },
        { key: "settingsStatusMarried", label: "Settings page: relationship status option (married)", default: "Married" },
        { key: "settingsStatusComplicated", label: "Settings page: relationship status option (complicated)", default: "It's complicated" },
        { key: "settingsGenderLabel", label: "Settings page: gender field", default: "Gender" },
        { key: "settingsGenderMale", label: "Settings page: gender option (male)", default: "Male" },
        { key: "settingsGenderFemale", label: "Settings page: gender option (female)", default: "Female" },
        { key: "settingsBioLabel", label: "Settings page: bio field", default: "Bio" },
        { key: "settingsBioPlaceholder", label: "Settings page: bio placeholder", default: "A few words about yourself…" },
        { key: "settingsSave", label: "Settings page: save button", default: "Save changes" },
        { key: "settingsSaved", label: "Settings page: toast after saving", default: "Profile updated" },
        { key: "settingsSaveFailed", label: "Settings page: toast when saving fails", default: "Couldn't save your changes. Please try again." },
        { key: "settingsLoadFailed", label: "Settings page: toast when the profile can't be loaded", default: "Couldn't load your profile. Please refresh the page." },
        { key: "settingsPhotoFailed", label: "Settings page: toast when the photo uploader can't open", type: "textarea", default: "Couldn't open the photo uploader. Check your connection or ad blocker and try again." },
        { key: "settingsDangerTitle", label: "Settings page: delete account box title", default: "Danger zone" },
        { key: "settingsDangerText", label: "Settings page: delete account box text", type: "textarea", default: "Deleting your account is permanent and can't be undone. Your profile will be removed." },
        { key: "settingsDeleteButton", label: "Settings page: delete account button", default: "Delete account" },
        { key: "settingsDeleteConfirm", label: "Settings page: first question before deleting the account", type: "textarea", default: "Are you sure you want to delete your account? This can't be undone." },
        { key: "settingsDeleteConfirmFinal", label: "Settings page: last question before deleting the account", type: "textarea", default: "Final warning: your account and profile will be permanently deleted. Continue?" },
        { key: "settingsDeleteRelogin", label: "Settings page: toast when the user must log in again to delete", type: "textarea", default: "For your security, log out and log in again, then delete your account." },
        { key: "settingsDeleteFailed", label: "Settings page: toast when deleting the account fails", default: "Couldn't delete your account. Please try again." },

        // Write an article page (/write)
        { key: "writeSeoTitle", label: "Write page: Google title", default: "Write an article" },
        { key: "writeSeoDescription", label: "Write page: Google description", type: "textarea", default: "Share your knowledge and publish technical articles on GTech." },
        { key: "writeLockedTitle", label: "Write page: title for logged-out visitors", default: "Write an article" },
        { key: "writeLockedDescription", label: "Write page: text for logged-out visitors", default: "Log in to write and publish your article." },
        { key: "writeTitle", label: "Write page: title", default: "Write an article" },
        { key: "writeDescription", label: "Write page: text under the title", default: "Share your knowledge with the community" },
        { key: "writeTitleLabel", label: "Write page: article title field", default: "Title" },
        { key: "writeTitlePlaceholder", label: "Write page: article title placeholder", default: "A clear, catchy title…" },
        { key: "writeEnhanceTitle", label: "Write page: improve title button (AI)", default: "Improve title" },
        { key: "writeEnhanceTitleTooltip", label: "Write page: tooltip of the improve title button", default: "Improve the title with AI" },
        { key: "writeGenerate", label: "Write page: generate article button (AI)", default: "Generate with AI" },
        { key: "writeContentLabel", label: "Write page: content field", default: "Content" },
        { key: "writeContentPlaceholder", label: "Write page: content placeholder", default: "Write your article here…" },
        { key: "writeShuffleImage", label: "Write page: shuffle cover image button", default: "Shuffle image" },
        { key: "writeAiImage", label: "Write page: new cover image button (AI)", default: "New image with AI" },
        { key: "writeImageUrlLabel", label: "Write page: cover image link field", default: "Cover image link" },
        { key: "writeImageUrlPlaceholder", label: "Write page: cover image link placeholder", default: "Paste the link of an image you picked…" },
        { key: "writeImageSuggestion", label: "Write page: suggested image search", default: "Suggested search: {query}", hint: "{query} = search words suggested by the AI" },
        { key: "writeSearchGoogle", label: "Write page: search Google Images button", default: "Search Google Images" },
        { key: "writeSearchUnsplash", label: "Write page: search Unsplash button", default: "Search Unsplash" },
        { key: "writeSummaryLabel", label: "Write page: Google description field (SEO)", default: "Search description" },
        { key: "writeSummaryPlaceholder", label: "Write page: Google description placeholder", default: "A short summary shown in Google results…" },
        { key: "writeTagsLabel", label: "Write page: tags field (SEO)", default: "Tags" },
        { key: "writeTagsPlaceholder", label: "Write page: tags placeholder", default: "Keywords, separated by commas…" },
        { key: "writeAdminHint", label: "Write page: note next to the publish button (admins)", default: "Publishes instantly" },
        { key: "writeUserHint", label: "Write page: note next to the publish button (members)", default: "Reviewed before publishing" },
        { key: "writePublish", label: "Write page: publish button", default: "Publish article" },
        { key: "writeTitleRequired", label: "Write page: message when the title is empty", default: "Write a title first." },
        { key: "writeContentRequired", label: "Write page: message when the content is empty", default: "Write the article content first." },
        { key: "writeSubmitted", label: "Write page: toast after sending an article for review", type: "textarea", default: "Article submitted. It will be published after review." },
        { key: "writePublished", label: "Write page: toast after publishing (admins)", default: "Article published" },
        { key: "writePublishFailed", label: "Write page: toast when publishing fails", default: "Couldn't publish the article. Please try again." },
        { key: "writeImageShuffled", label: "Write page: toast after shuffling the image", default: "Image changed" },
        { key: "writeAiImageLoading", label: "Write page: toast while the AI finds a new image", default: "Finding a new image…" },
        { key: "writeAiImageDone", label: "Write page: toast after the AI changed the image", default: "Image updated" },
        { key: "writeAiImageFailed", label: "Write page: toast when the AI image fails", default: "Couldn't update the image." },
        { key: "writeEnhanceLoading", label: "Write page: toast while the AI improves the title", default: "Improving the title…" },
        { key: "writeEnhanceDone", label: "Write page: toast after the AI improved the title", default: "Title improved" },
        { key: "writeEnhanceFailed", label: "Write page: toast when improving the title fails", default: "Couldn't improve the title." },
        { key: "writeGenerateLoading", label: "Write page: toast while the AI writes the article", default: "Writing the article and finding an image…" },
        { key: "writeGenerateDone", label: "Write page: toast after the AI wrote the article", type: "textarea", default: "Draft ready. Review it and pick a suitable image." },
        { key: "writeGenerateFailed", label: "Write page: toast when the AI can't write the article", default: "Couldn't generate the article: {error}", hint: "{error} = the technical reason" },

        // Edit post page (/edit/…)
        { key: "editSeoTitle", label: "Edit post page: browser tab title", default: "Edit post" },
        { key: "editLockedTitle", label: "Edit post page: title for logged-out visitors", default: "Edit post" },
        { key: "editLockedDescription", label: "Edit post page: text for logged-out visitors", default: "Log in to edit your posts." },
        { key: "editBack", label: "Edit post page: back button", default: "Back" },
        { key: "editTitle", label: "Edit post page: title", default: "Edit post" },
        { key: "editPlaceholder", label: "Edit post page: post text placeholder", default: "What's on your mind? You can paste images." },
        { key: "editPhotos", label: "Edit post page: add photos button", default: "Photos" },
        { key: "editDelete", label: "Edit post page: delete button", default: "Delete" },
        { key: "editSave", label: "Edit post page: save button", default: "Save post" },
        { key: "editNoPermission", label: "Edit post page: toast when the post belongs to someone else", default: "You don't have permission to edit this post." },
        { key: "editNotFound", label: "Edit post page: toast when the post doesn't exist", default: "Post not found." },
        { key: "editLoadFailed", label: "Edit post page: toast when the post can't be loaded", default: "Couldn't load the post." },
        { key: "editMaxImages", label: "Edit post page: toast for too many images", default: "You can upload up to 4 images." },
        { key: "editImagesAttached", label: "Edit post page: toast after attaching images", default: "{count} image(s) attached", hint: "{count} = number of images" },
        { key: "editUploadFailed", label: "Edit post page: toast when an image upload fails", default: "Couldn't upload the image. Please try again." },
        { key: "editImageUpdated", label: "Edit post page: toast after saving an edited image", default: "Image updated" },
        { key: "editImageUpdateFailed", label: "Edit post page: toast when saving an edited image fails", default: "Couldn't save the edited image." },
        { key: "editSaved", label: "Edit post page: toast after saving the post", default: "Post updated" },
        { key: "editSaveFailed", label: "Edit post page: toast when saving the post fails", default: "Couldn't update the post. Please try again." },
        { key: "editDeleteConfirm", label: "Edit post page: question before deleting the post", default: "Delete this post? This can't be undone." },
        { key: "editDeleted", label: "Edit post page: toast after deleting the post", default: "Post deleted" },
        { key: "editDeleteFailed", label: "Edit post page: toast when deleting the post fails", default: "Couldn't delete the post. Please try again." },

        // Image editor (opens from the post composer and the edit post page)
        { key: "editorTitle", label: "Image editor: title", default: "Edit image" },
        { key: "editorUndo", label: "Image editor: tooltip of the undo button", default: "Undo (Ctrl+Z)" },
        { key: "editorCancel", label: "Image editor: cancel button", default: "Cancel" },
        { key: "editorSave", label: "Image editor: save button", default: "Save" },
        { key: "editorDone", label: "Image editor: done button (closes the current tool)", default: "Done" },
        { key: "editorCrop", label: "Image editor: crop tool", default: "Crop" },
        { key: "editorBlur", label: "Image editor: blur tool", default: "Blur" },
        { key: "editorBrush", label: "Image editor: brush tool", default: "Brush" },
        { key: "editorText", label: "Image editor: text tool", default: "Text" },
        { key: "editorCropHint", label: "Image editor: crop tool hint", default: "Drag to select the area to keep" },
        { key: "editorBlurHint", label: "Image editor: blur tool hint", default: "Drag over the area to blur. You can blur several areas." },
        { key: "editorBrushHint", label: "Image editor: brush tool hint", default: "Draw on the image" },
        { key: "editorTextHint", label: "Image editor: text tool hint", default: "Click the image where the text should go" },
        { key: "editorApplyCrop", label: "Image editor: apply crop button", default: "Apply crop" },
        { key: "editorApplyBlur", label: "Image editor: apply blur button", default: "Apply blur" },
        { key: "editorColor", label: "Image editor: color picker", default: "Color" },
        { key: "editorSize", label: "Image editor: size slider", default: "Size" },
        { key: "editorOpacity", label: "Image editor: opacity slider", default: "Opacity" },
        { key: "editorHardness", label: "Image editor: hardness slider", default: "Hardness" },
        { key: "editorAlignLeft", label: "Image editor: align text left", default: "Align left" },
        { key: "editorAlignCenter", label: "Image editor: align text center", default: "Align center" },
        { key: "editorAlignRight", label: "Image editor: align text right", default: "Align right" },
        { key: "editorLtr", label: "Image editor: left-to-right text button", default: "LTR" },
        { key: "editorRtl", label: "Image editor: right-to-left text button", default: "RTL" },
        { key: "editorTextPlaceholder", label: "Image editor: text box placeholder", default: "Type…" },
        { key: "editorSaveFailed", label: "Image editor: toast when saving fails", default: "Couldn't save the image." },
        { key: "editorCropFailed", label: "Image editor: toast when cropping fails", default: "Couldn't crop the image." },
        { key: "editorBlurFailed", label: "Image editor: toast when blurring fails", default: "Couldn't blur the image." },
    ],
} as const satisfies CopySection;
