import type { CopySection } from "@/lib/copy/types";

export const homeCopy = {
    id: "home",
    title: "Home page (feed)",
    description: "The home page's Google title and description are the site-wide ones in the SEO section.",
    fields: [
        {
            key: "introTitle",
            label: "Main heading at the top of the home page (the page's H1: say what GTech does)",
            default: "Custom ERP, CRM and business software, built around how your company works",
        },
        {
            key: "introText",
            label: "Line under the main heading",
            default:
                "GTech is Gamal Abdelaty's software studio in Cairo, Egypt. We analyze how your business works, then build the ERP, CRM, web application or website that fits it, plus Shopify stores and hosting.",
        },
        { key: "allServices", label: "Link to the services page, after the service links", default: "All services" },
        { key: "typeProject", label: "Feed label for projects", default: "Project" },
        { key: "typeArticle", label: "Feed label for articles", default: "Article" },
        { key: "typePost", label: "Feed label for community posts", default: "Post" },
        { key: "showMore", label: "Expand a long post", default: "Show more" },
        { key: "showLess", label: "Collapse a long post", default: "Show less" },
        { key: "readArticle", label: "Link under an article in the feed", default: "Read the article" },
        { key: "comment", label: "Comment button", default: "Comment" },
        { key: "share", label: "Share button", default: "Share" },
        { key: "linkCopied", label: "Toast after copying a post link", default: "Link copied to clipboard" },
        { key: "feedEnd", label: "Message at the end of the feed", default: "You've reached the end" },
        { key: "feedError", label: "Feed failed to load", default: "Couldn't load the feed." },
        { key: "retry", label: "Retry button", default: "Retry" },
        { key: "composerPlaceholder", label: "Post composer placeholder", default: "Share an update… (you can paste images)" },
        { key: "composerPhotos", label: "Post composer: add photos button", default: "Photos" },
        { key: "composerAdminHint", label: "Post composer hint for admins", default: "Publishes instantly" },
        { key: "composerUserHint", label: "Post composer hint for members", default: "Reviewed before publishing" },
        { key: "composerPublish", label: "Post composer button (admins)", default: "Publish" },
        { key: "composerPost", label: "Post composer button (members)", default: "Post" },
        { key: "postPublished", label: "Toast: post published", default: "Post published" },
        { key: "postPending", label: "Toast: post waiting for approval", default: "Post submitted. It will appear once an admin approves it." },
        { key: "imagesAttached", label: "Toast: images attached", default: "{count} image(s) attached", hint: "{count} = number of images" },
        { key: "loadFailed", label: "Toast: feed failed to load", default: "Failed to load content" },
        { key: "copyFailed", label: "Toast: copying the link failed", default: "Failed to copy link." },
        { key: "maxImages", label: "Toast: too many images", default: "You can upload a maximum of 4 images." },
        { key: "uploadFailed", label: "Toast: image upload failed", default: "Failed to upload image. Please try again." },
        { key: "imageUpdated", label: "Toast: edited image saved", default: "Image updated" },
        { key: "imageUpdateFailed", label: "Toast: saving the edited image failed", default: "Failed to update edited image." },
        { key: "postFailed", label: "Toast: publishing the post failed", default: "Failed to submit post. Please try again." },
    ],
} as const satisfies CopySection;
